export const keyPoints: Record<number, string[]> = {
  1: [
    "Modern science: systematic study of the physical/material world through observation and experimentation",
    "Classical definition is broader (includes theological science)",
    "Scientific materialism (A) vs. science studies only some aspects of reality (B)",
    "Science cannot study immaterial entities, so it cannot prove materialism is correct",
    "This is a philosophical/metaphysical question, not a scientific one",
  ],
  2: [
    "Defined dependent variable (what you are measuring)",
    "Proper control group for the experimental group",
    "Independent variables minimized (isolate the variable of interest)",
    "Large enough sample size (small samples allow outliers to skew results)",
    "Results evaluated statistically",
    "Experiment is repeatable",
  ],
  3: [
    "Scientific fact: observation repeatedly confirmed by anyone with proper equipment",
    "Scientific hypothesis: working assumption to inform experiments or explain data",
    "Scientific theory: conceptual framework that explains observations and predicts new ones",
    "Characteristics of a good theory: physical phenomena, well-supported, broad scope, makes predictions, empirically testable",
    "Theories are 'fruitful and useful' not 'true' — all theories are tentative and subject to revision",
  ],
  4: [
    "Bar graphs: compare differences between groups or treatments; error bars show variability; p value assesses statistical significance",
    "XY plots: show correlation between two variables; best-fit line drawn",
    "R value: 1 = perfect correlation, 0 = no correlation",
    "P value: probability result occurred by chance; low p value = statistically significant",
    "Correlation does not imply causation",
  ],
  5: [
    "Homeostasis = stable internal environment = life; requires energy",
    "Equilibrium = balanced forces, no net movement = death",
    "Body maintains: temperature, pH, glucose, CO2, O2, Na, K, Ca, blood pressure",
    "Too high: heat stroke (temp), alkalosis (pH), diabetes (glucose)",
    "Too low: hypothermia (temp), acidosis (pH), hypoglycemia (glucose)",
    "The organ systems maintain these values; organ systems depend on healthy cells",
  ],
  6: [
    "Negative feedback: body senses a change and reacts AGAINST it",
    "Detector: hypothalamus (for temperature)",
    "Temp up → sweating + vasodilation (cool the body)",
    "Temp down → shivering + vasoconstriction (conserve heat)",
    "Properties: negative feedback, varies in reaction time (seconds to hours), hierarchy of control, requires energy",
  ],
  7: [
    "Characteristics of life: metabolize/grow, reproduce, respond to stimuli, complex organization, evolve, DNA/RNA, repair themselves, maintain homeostasis",
    "Organization is essential: cells are alive due to their dynamic organization",
    "Cell components in a tube ≠ cell (missing the complex organization)",
    "Scattered organs ≠ human being (organization and relationships matter)",
    "Atoms and molecules are non-living, but organized into cells they become living",
  ],
  8: [
    "Solubility: many molecules dissolve in water → move through blood and cells",
    "Heat capacity: absorbs large heat → helps stabilize body temperature",
    "Reactivity: breaks and forms molecular bonds",
    "High surface tension: allows water to hold together",
    "Wide fluidity range: stays liquid across a wide temperature range",
    "Polar covalent bonds: allows water to stick to itself (cohesion) and to other polar molecules",
  ],
  9: [
    "Carbohydrates: 1-2% of body; dissolve well in water; move through blood",
    "Functions: energy storage (glycogen in liver/muscles ~1 day) and cell recognition",
    "Simple: monosaccharides (glucose) and disaccharides (lactose, sucrose)",
    "Complex/polysaccharides: starch (from plants, digested for energy), cellulose/fiber (feeds GI bacteria), glycogen (body's storage form)",
    "Starch → most caloric content of the polysaccharides",
  ],
  10: [
    "Proteins: ~20% of body; contain nitrogen; dissolve in water",
    "Made of chains of 20 amino acid types; 9 essential (must come from diet)",
    "Require specific 3D shape to function; denaturation = unfolding = loss of function",
    "Denaturation causes: heat, acid, high salt",
    "Functions: structure (collagen = most abundant), catalysis (enzymes), transport/movement (hemoglobin, muscle proteins), recognition/protection (antibodies, clotting proteins)",
  ],
  11: [
    "Lipids: 15-30% of body; do NOT dissolve in water; transported by proteins in blood",
    "Building blocks: saturated (solid at room temp) and unsaturated (liquid at room temp) fatty acids",
    "Triglycerides: 3 fatty acids; functions: energy storage (~3-4 weeks), insulation, organ cushioning",
    "Phospholipids: 2 fatty acid tails + phosphate head; form cell membrane bilayer; hydrophilic head faces water, hydrophobic tails hidden",
    "Steroids: derived from cholesterol; include testosterone and estrogen (sex hormones)",
  ],
  12: [
    "LDL: transports cholesterol from liver to cells (bad cholesterol)",
    "HDL: transports excess cholesterol back to liver (good cholesterol)",
    "Atherosclerosis: fat plaque under arterial wall; first step is inflammation; high CRP is a stronger risk factor than high LDL",
    "Essential fat: males ~3%, females ~12%; needed for cellular function and hormones",
    "Storage fat: visceral (around organs) and subcutaneous (under skin) adipose tissue",
    "High body fat risks: obesity, type 2 diabetes, coronary heart disease",
    "Low body fat risks: fatigue, poor immunity, hormone imbalances, osteoporosis",
  ],
  13: [
    "GI tract: 30-foot tube from mouth to anus; small intestine = majority",
    "Accessory organs: teeth, tongue, liver, gallbladder, pancreas, salivary glands",
    "Mechanical digestion: physical breakdown; chemical digestion: break macromolecules into building blocks",
    "Oral cavity: teeth/tongue (mechanical) + salivary enzymes (digest sugars/fats); 1-1.5 L saliva/day",
    "Stomach: churning + HCl + proteases; chyme = acidic liquid (pH 1); lined with mucous; essential function = intrinsic factor (B12 absorption)",
    "Peptic ulcers: caused by H. pylori bacteria; treated with antibiotics + pH-raising drugs",
  ],
  14: [
    "Chyme enters duodenum → activates pancreas (enzymes) and liver/gallbladder (bile)",
    "Bile: produced by liver, stored by gallbladder, emulsifies fat (like detergent on grease)",
    "Pancreatic juice: enzymes for digesting fats, carbs, and proteins",
    "Small intestine: folded surface → large surface area; cells absorb amino acids, monosaccharides, fatty acids into blood; requires energy",
    "Large intestine: bacteria ferment cellulose, produce vitamins K and B5; 2-3 lbs bacteria; diverse ecosystem linked to better health",
  ],
  15: [
    "Fats: 9 cal/g; carbs and proteins: 4 cal/g — fats are more energy dense",
    "BMR (Basal Metabolic Rate): energy to sustain basic functions; measured by O2 consumption under standardized conditions",
    "Order of fuel use: Carbs first (~1 day stored) → Fats second (~3-4 weeks stored) → Proteins last (no reserves)",
    "Carbs: fastest energy; only fuel that works in low-oxygen conditions",
    "Proteins: produce nitrogen waste → requires extra energy to remove; not a good energy source",
  ],
  16: [
    "Low-fat diet: no good evidence it prevents heart disease",
    "Glycemic index: 1-100 scale; measures blood sugar spike; glucose = 100",
    "High glycemic load linked to type II diabetes (2.47x relative risk), obesity, heart disease",
    "Appetite: stretch receptors (fullness), nutrients in blood (satiation), leptin (fat → satiation), insulin (pancreas → satiation), ghrelin (empty stomach → hunger)",
    "Obesity: leptin/insulin resistance; gastric bypass and banding work mechanically + hormonally",
    "BMI = mass(kg)/height(m)2; only severely obese and underweight show significantly higher mortality risk",
  ],
  17: [
    "Nucleotides A, T, G, C are building blocks; DNA is double-stranded with A-T and G-C base pairs",
    "Human genome: 6 billion base pairs; 23 pairs of chromosomes (22 autosomes + 1 sex chromosome pair)",
    "XX = female, XY = male; ~20,000 genes; 95% of DNA is non-coding",
    "Gene: region of chromosome with info to make a protein",
    "Allele: one version of a specific gene; dominant (1 copy needed) vs. recessive (2 copies needed)",
    "Heterozygous: 2 different alleles; Homozygous: 2 same alleles",
    "Genotype: allele combination; Phenotype: observed characteristic",
  ],
  18: [
    "Process: DNA → transcription → mRNA → translation (ribosome) → protein",
    "Transcription: DNA unwound, mRNA copy made, DNA restored; occurs in nucleus",
    "Translation: ribosome reads mRNA 3 nucleotides (codon) at a time; tRNA brings amino acids; protein assembled",
    "RNA intermediate: chromosomes too large to leave nucleus; RNA is a small, replaceable copy",
    "If RNA is damaged, new copy can be made from DNA; if DNA were damaged, gene lost permanently",
  ],
  19: [
    "Each parent passes one allele per gene to offspring via gametes (sperm/egg)",
    "Example: two carrier parents (TS/ts) → 25% TS/TS, 50% TS/ts, 25% ts/ts",
    "DNA damage from: normal metabolism, chemicals, UV radiation, viruses",
    "Mutations in gametes → inherited; somatic cell mutations → not inherited",
    "Single-gene defects: cystic fibrosis, hemophilia, dwarfism",
    "Polygenic traits: height, intelligence, schizophrenia — many genes + environment",
    "Trisomy: extra chromosome; Down syndrome = trisomy 21",
    "In utero: amniocentesis (1:300 risk), CVS (1:100, earlier), maternal blood (no risk, 10 weeks)",
  ],
  20: [
    "Restriction enzymes: cut DNA at specific sequences; used by bacteria against viruses",
    "Process: cut gene of interest → insert into plasmid → seal with ligase → inject into bacteria → bacteria produces protein",
    "Example: human insulin gene inserted into bacteria → commercial insulin production",
    "Recombinant DNA technology = recombining DNA from different organisms",
    "Other applications: interferon, antithrombin, research animals with specific diseases",
  ],
  21: [
    "Getting genes into plants: gene gun (DNA-coated bullets) or plant pathogens/viruses",
    "Plant modifications: increased nutrition, frost/drought resistance, pest/herbicide resistance (Bt toxin in corn)",
    "Risks to humans: minimal (increased allergy risk, insecticidal toxin side effects)",
    "Risks to environment: gene transfer to wild plants, loss of genetic diversity",
    "Livestock: inject multiple gene copies (PCR-amplified) into fertilized egg; < 2% success rate",
    "Livestock uses: human protein production in milk, increased production, research models",
  ],
  22: [
    "Goal: insert healthy gene into person with defective gene",
    "Methods: viral delivery (virus carries healthy gene into target cells), DNA aerosol, implanting altered cells",
    "Successes: some immune deficiencies, hemophilia, blindness treated",
    "Limitations: only single-gene defects (not polygenic); immune reaction to virus/DNA can be lethal; may only correct a few cells",
    "Example: cystic fibrosis — extract lung cells, infect with healthy-gene virus, reinsert cells",
  ],
  23: [
    "Cas9 enzyme cleaves DNA at sites matching guide RNA (gRNA) sequence",
    "Matched DNA can be inserted during normal cellular DNA repair",
    "Chinese attempt (B-thalassemia): 28% efficacy, high off-target insertions",
    "US attempt (MYBPC3/hypertrophic cardiomyopathy): better efficacy, no off-target insertions identified",
    "Scientific issues: low efficiency, off-target mutations, mosaic nature of modification",
    "Ethical debate: curing disease vs. designer babies",
  ],
  24: [
    "~20 trillion cells in human body; 200+ specialized types; all arise from undifferentiated stem cells",
    "Progression: Totipotent → Pluripotent → Multipotent → Specialized",
    "Cancer cells: lose specialization, divide faster, increased metabolism, smaller and unspecialized",
    "Normal cells: differentiated, specific shape, regulated division",
    "Cell cycle: G1 (normal function) → S (DNA replication) → G2 (prep) → Mitotic phase (division)",
    "Neurons permanently arrested in G1; never divide",
  ],
  25: [
    "Cells divide when: nutrients present, sufficient size, growth factors present",
    "Cells stop dividing when: crowded, nutrients/growth factors lacking, DNA damaged",
    "G1-S checkpoint: main checkpoint — checks everything (nutrients, size, DNA integrity, growth factors)",
    "G2-M checkpoint: ensures DNA has replicated properly before cell divides",
    "Cancer = checkpoints no longer function properly → unregulated division",
  ],
  26: [
    "Benign tumor: stays localized; can be surgically removed",
    "Malignant tumor: metastatic — cells detach and spread through bloodstream to other organs",
    "Causes of DNA damage: normal metabolism, carcinogens (chemicals, radiation, viruses); 60-70% from environmental agents",
    "Multiple mutations required: single mutation rarely causes cancer; need several mutations in same cell",
    "Oncogenes: mutated genes that drive unregulated division (e.g., growth factor receptor stuck in 'on' position)",
    "Tumor suppressor genes (p53): detect DNA damage → stop division → allow repair → if unrepaired, trigger apoptosis",
    "P53 mutated in most tumors",
  ],
  27: [
    "Surgery: removes tumor; only effective before metastasis",
    "Radiation: irradiates and kills tumor cells; non-specific",
    "Chemotherapy: toxic chemicals; targets fast-dividing and metabolically active cells; non-specific; damages hair follicles, GI lining, etc.",
    "Gleevec (targeted): binds to abnormal protein in Chronic Myeloid Leukemia; healthy cells unaffected",
    "Anti-angiogenesis factors: block tumor blood vessel growth; limits tumor size",
    "Gene therapy (future): insert healthy p53 into tumors — not yet successfully done",
  ],
  28: [
    "Antigens: foreign substances (bacterial membranes, viral particles, foreign blood cells) that trigger immune response",
    "Blood group antigens (A, B, O): body attacks antigens not recognized as self",
    "Leukocytes (white blood cells): phagocytes + lymphocytes",
    "Phagocytes: engulf and destroy most pathogens; neutrophils (60-70%), monocytes (3-8%)",
    "Lymphocytes (25-33%): B cells (secrete antibodies) and cytotoxic T cells (kill infected cells)",
    "B and T cells: formed in bone marrow; must be immunocompetent and not self-reactive",
  ],
  29: [
    "Physical/chemical barriers: skin, sweat, mucous, stomach pH",
    "Non-specific: fever and inflammation → increased blood flow → more phagocytes to site",
    "Phagocytes: first line; engulf bacteria; activate lymphocytes",
    "B cell activation: specific antibody binds antigen → B cell clones → plasma cells (flood antibodies, then die) + memory cells (persist years)",
    "Cytotoxic T cells: recognize viral antigens on infected cell surfaces → kill those cells → prevent viral replication",
    "Antibodies: two binding sites; make pathogens easier to phagocytose; prevent cell binding; activate complement; neutralize toxins",
  ],
  30: [
    "Vaccines expose body to non-infectious antigen → memory B and T cells formed",
    "On re-exposure: faster, stronger response (no need to ramp up from scratch)",
    "Inactivated vaccines: pathogen killed; risk of altered antigens",
    "Attenuated vaccines: pathogen genetically modified to be non-pathogenic; rare risk of reversion",
    "Risks: mild inflammation (usual); rare serious reactions (1:100,000-1:1,000,000); no scientific link to autism (key study retracted)",
    "Ethics: some vaccines produced using fetal cell lines; permissible if grave disease, no alternatives, objections registered",
  ],
  31: [
    "Auto-immune: immune system attacks body's own cells/antigens",
    "Symptoms: almost always involve inflammation; can affect one or many organs",
    "Examples: arthritis, type 1 diabetes, hepatitis, multiple sclerosis, psoriasis",
    "Treatments: immunosuppressants (corticosteroids), drugs for damaged tissue (e.g., joint supplements)",
    "Causes: proteins altered by drugs/chemicals → appear foreign; cross-reactive microbial antigens; genetic mutations create new self-antigens; normally hidden proteins become exposed; virus-infected cell attacks destroy too many cells",
  ],
};
